machinetranslationsite/machinetranslationsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'))
]

machinetranslationsite/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import redirect
from .views import translator_english, TranslationHistoryView


def user_not_logged(user):
    return not user.is_authenticated


def redirect_authenticated_user(request):
    if request.user.is_authenticated:
        return redirect('site:loggedinhome')  # Change 'your_redirect_url' to the desired URL
    return True


app_name = 'site'
urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True),
         name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('logged/', views.loggedinhome, name='loggedinhome'),
    path('password/', views.password, name='password'),
    path('password_reset/',
         user_passes_test(user_not_logged, login_url='site:loggedinhome')(auth_view.PasswordResetView.as_view(
             template_name='users/password_reset/password_reset.html',
             success_url=reverse_lazy('site:password_reset_done'),
             email_template_name='users/password_reset/password_reset_email.html',
             subject_template_name='users/password_reset/password_reset_subject.txt'
         )),
         name='password_reset'),
    path('password_reset_done/',
         user_passes_test(user_not_logged, login_url='site:home')(
             auth_view.PasswordResetDoneView.as_view(template_name='users/password_reset/password_reset_sent.html')),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>',
         user_passes_test(user_not_logged, login_url='site:home')(
             auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset/password_reset_form.html',
                                                        success_url=reverse_lazy('site:password_reset_complete'))),
         name='password_reset_confirm'),
    path('password_reset_complete/',
         user_passes_test(user_not_logged, login_url='site:home')(auth_view.PasswordResetCompleteView.as_view(
             template_name='users/password_reset/password_reset_success.html')),
         name='password_reset_complete'),
    path('translateenglish/', views.translator_english, name='translatorEnglish'),
    path('translateturkish/', views.translator_turkish, name='translatorTurkish'),
    path('translate/', views.translate, name='translate'),
    path('translationhistory/', TranslationHistoryView.as_view(), name='translationHistory')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

machinetranslationsite/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pictures')


def __str__(self):
    return f'{self.user.username} profile'


class TranslationTask(models.Model):
    input_text = models.TextField()
    output_text = models.TextField()


class TranslationHistory(models.Model):
    source_text = models.TextField()
    target_text = models.TextField()
    source_language = models.CharField(max_length=255)
    target_language = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def clear_history(cls):
        cls.objects.all().delete()

    def __str__(self):
        return f"{self.source_text} -> {self.target_text}"

machinetranslationsite/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    username = forms.CharField
    email = forms.EmailField

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    image = forms.ImageField

    class Meta:
        model = Profile
        fields = ['image']


class TranslationFormEnglish(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 45}), initial='Hi, I am having a lovely day!')
    source_language = forms.CharField(initial='en', widget=forms.HiddenInput())
    target_language = forms.CharField(initial='tr', widget=forms.HiddenInput())


class TranslationFormTurkish(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 45}), initial="Merhaba, güzel bir gün geçiriyorum!")
    source_language = forms.CharField(initial='tr', widget=forms.HiddenInput())
    target_language = forms.CharField(initial='en', widget=forms.HiddenInput())

machinetranslationsite/users/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from transformers import MarianMTModel, MarianTokenizer
from django.views import View
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, TranslationFormEnglish, TranslationFormTurkish
from .models import TranslationHistory


# Create your views here.

def home(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/logged')
    return render(request, 'users/home.html')


def login(request):
    return render(request, 'users/login.html')


@login_required(login_url="/login")
def loggedinhome(request):
    return render(request, 'users/loggedinhome.html')


@login_required(login_url="/login")
def translate(request):
    return render(request, 'users/translation/translate_landing.html')


def logout(request):
    return render(request, 'users/logout.html')


@login_required(login_url="/login")
def password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Keeps the user logged in
            messages.success(request, f'Your password was updated successfully.')
            return redirect(reverse('site:password'))
        else:
            messages.error(request, f'Please correct the error below.')

    else:
        form = PasswordChangeForm(request.user)

    context = {
        "form": form
    }

    return render(request, 'users/password.html', context)


def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/logged')
    form = UserRegisterForm()

    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,
                             f'Hi {username}, your account was created successfully. Please login to continue.')
            return redirect(reverse('site:home'))

    return render(request, 'users/register.html', {'form': form})


@login_required(login_url="/login")
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your profile was updated successfully.')
            return redirect(reverse('site:profile'))

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        "u_form": u_form,
        "p_form": p_form
    }
    return render(request, 'users/profile.html', context)


def translate_english(text, source_lang, target_lang):
    model_name = f'Helsinki-NLP/opus-tatoeba-en-tr'
    model = MarianMTModel.from_pretrained(model_name)
    tokenizer = MarianTokenizer.from_pretrained(model_name)

    inputs = tokenizer(text, return_tensors="pt")
    outputs = model.generate(**inputs)

    translated_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]

    # Check if the current translation exists in history
    existing_translations = TranslationHistory.objects.filter(
        source_text=text,
        target_text=translated_text,
        source_language=source_lang,
        target_language=target_lang
    ).first()

    if not existing_translations:
        TranslationHistory.objects.create(
            source_text=text,
            target_text=translated_text,
            source_language=source_lang,
            target_language=target_lang
        )

    return translated_text


@login_required(login_url="/login")
def translator_english(request):
    if request.method == 'POST':
        form = TranslationFormEnglish(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            source_lang = form.cleaned_data['source_language']
            target_lang = form.cleaned_data['target_language']

            translated_text = translate_english(text, source_lang, target_lang)

            return render(request, 'users/translation/english_translator.html',
                          {'form': form, 'translated_text': translated_text})
    else:
        form = TranslationFormEnglish()

    return render(request, 'users/translation/english_translator.html', {'form': form})


def translate_turkish(text, source_lang, target_lang):
    model_name = f'Helsinki-NLP/opus-mt-tr-en'
    model = MarianMTModel.from_pretrained(model_name)
    tokenizer = MarianTokenizer.from_pretrained(model_name)

    inputs = tokenizer(text, return_tensors="pt")
    outputs = model.generate(**inputs)

    translated_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]

    # Check if the current translation exists in history
    existing_translations = TranslationHistory.objects.filter(
        source_text=text,
        target_text=translated_text,
        source_language=source_lang,
        target_language=target_lang
    ).first()

    if not existing_translations:
        TranslationHistory.objects.create(
            source_text=text,
            target_text=translated_text,
            source_language=source_lang,
            target_language=target_lang
        )

    return translated_text


@login_required(login_url="/login")
def translator_turkish(request):
    if request.method == 'POST':
        form = TranslationFormTurkish(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            source_lang = form.cleaned_data['source_language']
            target_lang = form.cleaned_data['target_language']

            translated_text = translate_turkish(text, source_lang, target_lang)
            return render(request, 'users/translation/turkish_translator.html',
                          {'form': form, 'translated_text': translated_text})
    else:
        form = TranslationFormTurkish()

    return render(request, 'users/translation/turkish_translator.html', {'form': form})


class TranslationHistoryView(LoginRequiredMixin, View):
    template_name = 'users/translation/translation_history.html'
    login_url = '/login'

    def get(self, request, *args, **kwargs):
        translations = TranslationHistory.objects.all()
        return render(request, self.template_name, {'translations': translations})

    def post(self, request, *args, **kwargs):
        if 'clear_history' in request.POST:
            TranslationHistory.clear_history()
            return redirect('site:translationHistory')

        allTranslations = TranslationHistory.objects.all()
        return render(request, "users/translation/translation_history.html", {"translations": allTranslations})

machinetranslationsite/users/templates/users/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Custom Google font-->
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="static/users/styles.css" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column h-100">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                    <a class="navbar-brand"><span class="fw-bolder text-primary">TurEng Translate</span></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                              {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'site:loggedinhome' %}">Home</a></li>
                            <li class="nav-item"><a class="nav-link" style="color:black">Hello, {{user.username}}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'site:translate' %}">Translate</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'site:translationHistory' %}">History</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'site:profile' %}">{{user.username}}'s Profile</a></li>
                           <form method="post" action="{% url 'site:logout' %}">
                            {% csrf_token %}
                          <button class="btn btn-primary" id="submitButton" type="submit">Logout</button>
                            </form>
                            {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'site:home' %}">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'site:login' %}">Login</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'site:register' %}">Register</a></li>
                           {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
      <div>
        {% if messages %}
         {% for message in messages %}
          <div class="alert alert-{{message.tags}}">{{message}}</div>
         {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
      </div>

            <footer class="bg-white py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0">TurEng Translate &middot; Turkish to English Translator</div></div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="users/scripts.js"></script>
    </body>
</html>

machinetranslationsite/users/templates/users/login.html
{% extends 'users/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'users/styles.css' %}">
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Login form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <img class="profile-img" src="{% static 'users/userpic.png' %}" alt="..." />
                            <h1 class="fw-bolder">Login</h1>
                            <p class="lead fw-normal text-muted mb-0">Login to continue translating!</p>
                        </div>
                        <div class="row gx-5 justify-content-center">
              <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          {{ form|crispy }}
           <div class="col-auto"><div class="small m-0">Forgot your password? <a href="{% url 'site:password_reset' %}">Reset it here</a></div></div>
      </fieldset>
        <div class="d-grid"> <button class="btn btn-primary" id="submitButton" style="margin:20px;" type="submit">Submit</button></div>
          <div class="col-auto"><div class="small m-0">Don't have an account? <a href="{% url 'site:register' %}">Register here</a></div></div>
    </form>
                        </div>
                    </div>
                </div>
            </section>
{% endblock %}

machinetranslationsite/users/templates/users/logout.html
{% extends 'users/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
 <link rel="stylesheet" href="{% static 'users/styles.css' %}">
<div class="container px-5 my-5">
                <div class="text-center mb-5">
                    <h1 class="display-5 fw-bolder mb-0"><span class="text-gradient d-inline">You have been logged out</span></h1>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-11 col-xl-9 col-xxl-8">
                        <section>
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <h2 class="text-primary fw-bolder mb-0">Login again &rarr;</h2>
                                <a class="btn btn-primary px-4 py-3" href="{% url 'site:login' %}">
                                    Login
                                </a>
                            </div>
                        </section>
{% endblock %}

machinetranslationsite/users/templates/users/password.html
{% extends 'users/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'users/styles.css' %}">
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Change password form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <h1 class="fw-bolder">Change password</h1>
                        </div>
                        <div class="row gx-5 justify-content-center">
              <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
                  <fieldset class="form-group">
          {{ form|crispy }}
      </fieldset>
        <div class="d-grid">
            <a class="btn px-5 py-3 me-sm-3 fs-6 fw-bolder"> <button class="btn btn-primary"  style="margin:20px; width: 100%" id="submitButton" type="submit">Submit</button></a>
        </div>
    </form>
                       <div class="d-grid">
                                <div class="col-lg-8">Go back to your profile:</div>
                                <a class="btn px-5 py-3 me-sm-3 fs-6 fw-bolder" href="/profile"><button class="btn btn-primary" style="margin:20px; width: 100%">Go back</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
{% endblock %}

machinetranslationsite/users/templates/users/profile.html
{% extends 'users/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'users/styles.css' %}">
<!-- Page Content-->
            <div class="container px-5 my-5">
                <!-- Profile Section-->
                <section>
                    <!-- Profile Card-->
                    <div class="card shadow border-0 rounded-4 mb-5">
                        <div class="card-body p-5">
                            <div class="row align-items-center gx-5">
                                <div class="col text-center text-lg-start mb-4 mb-lg-0">
                                    <div class="bg-light p-4 rounded-4">
                                        <div class="profile-container">
                                           <center><img src="{{ user.profile.image.url }}" alt="{{ user.profile }}'s picture" style="width:20%"></center>
                                        </div>
                                    </div>
                                </div>
                                <div class="text-center mb-5">
                                    <h1 class="display-5 fw-bolder mb-0"><span class="text-gradient d-inline">{{user.username}}</span></h1>
                                </div>
                            </div>
                            <div class="col-lg-8"><div>Your username: {{user.username}}</div>
                            <div class="col-lg-8" style="margin-bottom: 10px;"><div>Your email: {{user.email}}</div></div>
                            </div>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
      <fieldset class="form-group">
          {{ u_form|crispy }}
          {{ p_form|crispy }}
      </fieldset>
        <div class="d-grid">
            <a class="btn px-5 py-3 me-sm-3 fs-6 fw-bolder"> <button class="btn btn-primary"  style="margin:20px; width: 100%" id="submitButton" type="submit">Update profile</button></a>
        </div>
    </form>
                            <div class="d-grid">
                                <div class="col-lg-8">You can change your password by clicking below:</div>
                                <a class="btn px-5 py-3 me-sm-3 fs-6 fw-bolder" href="/password"><button class="btn btn-primary" style="margin:20px; width: 100%">Change password</button></a>
                            </div>


                        </div>
                    </div>
                </section>
                    </div>

                    {% endblock %}

machinetranslationsite/users/templates/users/register.html
{% extends 'users/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'users/styles.css' %}">
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Register form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                         <img class="profile-img" src="{% static 'users/registerpic.png' %}" alt="..." />
                            <h1 class="fw-bolder">Register</h1>
                            <p class="lead fw-normal text-muted mb-0">Register to start translating!</p>
                        </div>
                        <div class="row gx-5 justify-content-center">
              <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          {{ form|crispy }}
      </fieldset>
        <div class="d-grid"> <button class="btn btn-primary"  style="margin:20px;" id="submitButton" type="submit">Submit</button></div>
          <div class="col-auto"><div class="small m-0">Already have an account? <a href="{% url 'site:login' %}">Log in here</a></div></div>
    </form>
                        </div>
                    </div>
                </div>
            </section>
{% endblock %}