machinetranslationsite/machinetranslationsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'))
]

machinetranslationsite/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import redirect
from .views import translator_english, TranslationHistoryView


def user_not_logged(user):
    return not user.is_authenticated


def redirect_authenticated_user(request):
    if request.user.is_authenticated:
        return redirect('site:loggedinhome')  # Change 'your_redirect_url' to the desired URL
    return True


app_name = 'site'
urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True),
         name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('logged/', views.loggedinhome, name='loggedinhome'),
    path('password/', views.password, name='password'),
    path('password_reset/',
         user_passes_test(user_not_logged, login_url='site:loggedinhome')(auth_view.PasswordResetView.as_view(
             template_name='users/password_reset/password_reset.html',
             success_url=reverse_lazy('site:password_reset_done'),
             email_template_name='users/password_reset/password_reset_email.html',
             subject_template_name='users/password_reset/password_reset_subject.txt'
         )),
         name='password_reset'),
    path('password_reset_done/',
         user_passes_test(user_not_logged, login_url='site:home')(
             auth_view.PasswordResetDoneView.as_view(template_name='users/password_reset/password_reset_sent.html')),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>',
         user_passes_test(user_not_logged, login_url='site:home')(
             auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset/password_reset_form.html',
                                                        success_url=reverse_lazy('site:password_reset_complete'))),
         name='password_reset_confirm'),
    path('password_reset_complete/',
         user_passes_test(user_not_logged, login_url='site:home')(auth_view.PasswordResetCompleteView.as_view(
             template_name='users/password_reset/password_reset_success.html')),
         name='password_reset_complete'),
    path('translateenglish/', views.translator_english, name='translatorEnglish'),
    path('translateturkish/', views.translator_turkish, name='translatorTurkish'),
    path('translate/', views.translate, name='translate'),
    path('translationhistory/', TranslationHistoryView.as_view(), name='translationHistory')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

machinetranslationsite/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pictures')


def __str__(self):
    return f'{self.user.username} profile'


class TranslationTask(models.Model):
    input_text = models.TextField()
    output_text = models.TextField()


class TranslationHistory(models.Model):
    source_text = models.TextField()
    target_text = models.TextField()
    source_language = models.CharField(max_length=255)
    target_language = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def clear_history(cls):
        cls.objects.all().delete()

    def __str__(self):
        return f"{self.source_text} -> {self.target_text}"

machinetranslationsite/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    username = forms.CharField
    email = forms.EmailField

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    image = forms.ImageField

    class Meta:
        model = Profile
        fields = ['image']


class TranslationFormEnglish(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 45}), initial='Hi, I am having a lovely day!')
    source_language = forms.CharField(initial='en', widget=forms.HiddenInput())
    target_language = forms.CharField(initial='tr', widget=forms.HiddenInput())


class TranslationFormTurkish(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 45}), initial="Merhaba, güzel bir gün geçiriyorum!")
    source_language = forms.CharField(initial='tr', widget=forms.HiddenInput())
    target_language = forms.CharField(initial='en', widget=forms.HiddenInput())

machinetranslationsite/users/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from transformers import MarianMTModel, MarianTokenizer
from django.views import View
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, TranslationFormEnglish, TranslationFormTurkish
from .models import TranslationHistory


# Create your views here.

def home(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/logged')
    return render(request, 'users/home.html')


def login(request):
    return render(request, 'users/login.html')


@login_required(login_url="/login")
def loggedinhome(request):
    return render(request, 'users/loggedinhome.html')


@login_required(login_url="/login")
def translate(request):
    return render(request, 'users/translation/translate_landing.html')


def logout(request):
    return render(request, 'users/logout.html')


@login_required(login_url="/login")
def password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Keeps the user logged in
            messages.success(request, f'Your password was updated successfully.')
            return redirect(reverse('site:password'))
        else:
            messages.error(request, f'Please correct the error below.')

    else:
        form = PasswordChangeForm(request.user)

    context = {
        "form": form
    }

    return render(request, 'users/password.html', context)


def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/logged')
    form = UserRegisterForm()

    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,
                             f'Hi {username}, your account was created successfully. Please login to continue.')
            return redirect(reverse('site:home'))

    return render(request, 'users/register.html', {'form': form})


@login_required(login_url="/login")
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your profile was updated successfully.')
            return redirect(reverse('site:profile'))

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        "u_form": u_form,
        "p_form": p_form
    }
    return render(request, 'users/profile.html', context)


def translate_english(text, source_lang, target_lang):
    model_name = f'Helsinki-NLP/opus-tatoeba-en-tr'
    model = MarianMTModel.from_pretrained(model_name)
    tokenizer = MarianTokenizer.from_pretrained(model_name)

    inputs = tokenizer(text, return_tensors="pt")
    outputs = model.generate(**inputs)

    translated_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]

    # Check if the current translation exists in history
    existing_translations = TranslationHistory.objects.filter(
        source_text=text,
        target_text=translated_text,
        source_language=source_lang,
        target_language=target_lang
    ).first()

    if not existing_translations:
        TranslationHistory.objects.create(
            source_text=text,
            target_text=translated_text,
            source_language=source_lang,
            target_language=target_lang
        )

    return translated_text


@login_required(login_url="/login")
def translator_english(request):
    if request.method == 'POST':
        form = TranslationFormEnglish(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            source_lang = form.cleaned_data['source_language']
            target_lang = form.cleaned_data['target_language']

            translated_text = translate_english(text, source_lang, target_lang)

            return render(request, 'users/translation/english_translator.html',
                          {'form': form, 'translated_text': translated_text})
    else:
        form = TranslationFormEnglish()

    return render(request, 'users/translation/english_translator.html', {'form': form})


def translate_turkish(text, source_lang, target_lang):
    model_name = f'Helsinki-NLP/opus-mt-tr-en'
    model = MarianMTModel.from_pretrained(model_name)
    tokenizer = MarianTokenizer.from_pretrained(model_name)

    inputs = tokenizer(text, return_tensors="pt")
    outputs = model.generate(**inputs)

    translated_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]

    # Check if the current translation exists in history
    existing_translations = TranslationHistory.objects.filter(
        source_text=text,
        target_text=translated_text,
        source_language=source_lang,
        target_language=target_lang
    ).first()

    if not existing_translations:
        TranslationHistory.objects.create(
            source_text=text,
            target_text=translated_text,
            source_language=source_lang,
            target_language=target_lang
        )

    return translated_text


@login_required(login_url="/login")
def translator_turkish(request):
    if request.method == 'POST':
        form = TranslationFormTurkish(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            source_lang = form.cleaned_data['source_language']
            target_lang = form.cleaned_data['target_language']

            translated_text = translate_turkish(text, source_lang, target_lang)
            return render(request, 'users/translation/turkish_translator.html',
                          {'form': form, 'translated_text': translated_text})
    else:
        form = TranslationFormTurkish()

    return render(request, 'users/translation/turkish_translator.html', {'form': form})


class TranslationHistoryView(LoginRequiredMixin, View):
    template_name = 'users/translation/translation_history.html'
    login_url = '/login'

    def get(self, request, *args, **kwargs):
        translations = TranslationHistory.objects.all()
        return render(request, self.template_name, {'translations': translations})

    def post(self, request, *args, **kwargs):
        if 'clear_history' in request.POST:
            TranslationHistory.clear_history()
            return redirect('site:translationHistory')

        allTranslations = TranslationHistory.objects.all()
        return render(request, "users/translation/translation_history.html", {"translations": allTranslations})

machinetranslationsite/users/templates/users/password_reset/password_reset.html
{% extends 'users/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'users/styles.css' %}">
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Login form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <h1 class="fw-bolder">Password Reset Request</h1>
                              <p class="lead fw-normal text-muted mb-0">Enter your email to reset your password.</p>
                        </div>
                        <div class="row gx-5 justify-content-center">
              <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          {{ form|crispy }}
      </fieldset>
        <div class="d-grid"> <button class="btn btn-primary" id="submitButton" style="margin:20px;" type="submit">Request</button></div>
    </form>
                        </div>
                    </div>
                </div>
            </section>
{% endblock %}

machinetranslationsite/users/templates/users/password_reset/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at TurEng Translate.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'site:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using the site!" %}

{% blocktranslate %}The Developer{% endblocktranslate %}

{% endautoescape %}

machinetranslationsite/users/templates/users/password_reset/password_reset_form.html
{% extends 'users/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'users/styles.css' %}">
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Login form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <h1 class="fw-bolder">Password Reset Form</h1>
                              <p class="lead fw-normal text-muted mb-0">Enter your new password.</p>
                        </div>
                        <div class="row gx-5 justify-content-center">
              <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          {{ form|crispy }}
      </fieldset>
        <div class="d-grid"> <button class="btn btn-primary" id="submitButton" style="margin:20px;" type="submit">Reset</button></div>
    </form>
                        </div>
                    </div>
                </div>
            </section>
{% endblock %}

machinetranslationsite/users/templates/users/password_reset/password_reset_sent.html
{% extends 'users/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
 <link rel="stylesheet" href="{% static 'users/styles.css' %}">
<div class="container px-5 my-5">
                <div class="text-center mb-5">
                    <h1 class="display-5 fw-bolder mb-0"><span class="text-gradient d-inline">An email has been sent with instructions to reset your password.</span></h1>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-11 col-xl-9 col-xxl-8">
                        <section>
                        </section>
{% endblock %}

machinetranslationsite/users/templates/users/password_reset/password_reset_success.html
<!DOCTYPE html>
<html lang="en">
{% extends 'users/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
 <link rel="stylesheet" href="{% static 'users/styles.css' %}">
<div class="container px-5 my-5">
                <div class="text-center mb-5">
                    <h1 class="display-5 fw-bolder mb-0"><span class="text-gradient d-inline">Your password was reset successfully. Please log in to continue.</span></h1>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-11 col-xl-9 col-xxl-8">
                        <section>
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <h2 class="text-primary fw-bolder mb-0">Log in &rarr;</h2>
                                <a class="btn btn-primary px-4 py-3" href="{% url 'site:login' %}">
                                    Login
                                </a>
                            </div>
                        </section>
{% endblock %}